### ISSUE TITLE
Logo design for cf-saturn

### ISSUE THREAD

**Issue by zuuritaly** [mgenware/cf-saturn#4]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer

**Comment by mgenware** [comment]
Hi Zuur, really appreciate your interest in our project. I'm afraid we don't have a plan to change the logo for now, will contact you if there is interest. Thanks 😃
